const ROUTER_PATHS = {
    HOME: '/',
    SOBRE_NOS: '/sobre-nos',
    SOBRE_NOS_HISTORIA: '/sobre-nos/nossa-historia',
    SOBRE_NOS_TIMELINE: '/sobre-nos/linha-do-tempo',
    SOBRE_NOS_ATUACAO: '/sobre-nos/onde-atuamos',
    SOBRE_NOS_GESTAO: '/sobre-nos/modelo-de-gestao',
    PE_LUIS_CECCHIN: '/padre-luis-cecchin',
    PE_LUIS_CECCHIN_TESTAMENTOS: '/padre-luis-cecchin/testamentos',
    PE_LUIS_CECCHIN_MEMORIAL: '/padre-luis-cecchin/memorial',
    PE_LUIS_CECCHIN_CAUSA: '/padre-luis-cecchin/abertura-causa',
    PE_LUIS_CECCHIN_CENTENARIO: '/padre-luis-cecchin/centenario',
    ATIVIDADES: '/atividades',
    ATIVIDADES_CARIDADE: '/atividades/cantinho-caridade',
    ATIVIDADES_SOCIOFAMILIAR: '/atividades/sociofamiliar',
    ATIVIDADES_FORMACAO: '/atividades/formacao-geral',
    ATIVIDADES_CONVIVENCIA: '/atividades/servico-convivencia',
    ATIVIDADES_INFANTIL: '/atividades/politicas-publicas',
    PARCEIROS: '/parceiros',
    DOACAO: '/doacao',
    NOTICIAS: '/noticias',
    TRANSPARENCIA: '/transparencia',
    CONTATO: '/contato',
};

export default ROUTER_PATHS;